// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MIDL
{
    internal sealed partial class Vsix
    {
        public const string Id = "MIDL.148cb49f-0d60-482a-a9ca-800f2b6c579b";
        public const string Name = "IDL 3 Language Service";
        public const string Description = @"Provides language support for IDL 3 and header generation based on WinMD transformations.";
        public const string Language = "en-US";
        public const string Version = "1.0.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "idl, midl";
    }
}
