// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MIDL
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IdlFileSelectedString = "3af3801b-be4e-45a6-83c2-71ae3581a399";
        public static Guid IdlFileSelected = new Guid(IdlFileSelectedString);

        public const string MidlEditorFactoryString = "f7d6e464-2c5c-4e02-bc1b-8fe2cde367a3";
        public static Guid MidlEditorFactory = new Guid(MidlEditorFactoryString);

        public const string MIDLString = "be7365f7-d75c-4cfe-94b5-e28bf78459b5";
        public static Guid MIDL = new Guid(MIDLString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}